services:
  web:
    build: .
    ports:
      - 8080:80
    volumes:
      - "./php:/var/www/html"
  db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=ciccio
    volumes:
      - "./mysql:/var/lib/mysql"
